package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DeloviIzraboteniOdMaterijal generated by hbm2java
 */
@Entity
@Table(name = "delovi_izraboteni_od_materijal")
@Getter
@Setter
public class DeloviIzraboteniOdMaterijal {

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "delovi"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "id_del", unique = true, nullable = false)
    private Long idDel;
    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    private Delovi delovi;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_materijal", nullable = false)
    private Materijali materijali;

    public DeloviIzraboteniOdMaterijal() {
    }

    public DeloviIzraboteniOdMaterijal(Delovi delovi, Materijali materijali) {
        this.delovi = delovi;
        this.materijali = materijali;
    }


}


