package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Direktor generated by hbm2java
 */
@Entity
@Table(name = "direktor")
@Getter
@Setter
public class Direktor {

    @Id
    @Column(name = "id_vraboten", unique = true, nullable = false)
    private Long idVraboten;
    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    private Vraboteni vraboteni;

    public Direktor() {
    }

    public Direktor(Vraboteni vraboteni) {
        this.vraboteni = vraboteni;
    }


}


