package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dogovori generated by hbm2java
 */
@Entity
@Table(name="dogovori"
)
public class Dogovori  implements java.io.Serializable {


     private int idDogovor;
     private Vraboteni vraboteni;
     private Date pocetok;
     private double plata;
     private Date kraj;
     private short aktiven;

    public Dogovori() {
    }

	
    public Dogovori(int idDogovor, Date pocetok, double plata, Date kraj, short aktiven) {
        this.idDogovor = idDogovor;
        this.pocetok = pocetok;
        this.plata = plata;
        this.kraj = kraj;
        this.aktiven = aktiven;
    }
    public Dogovori(int idDogovor, Vraboteni vraboteni, Date pocetok, double plata, Date kraj, short aktiven) {
       this.idDogovor = idDogovor;
       this.vraboteni = vraboteni;
       this.pocetok = pocetok;
       this.plata = plata;
       this.kraj = kraj;
       this.aktiven = aktiven;
    }
   
     @Id 

    
    @Column(name="id_dogovor", unique=true, nullable=false)
    public int getIdDogovor() {
        return this.idDogovor;
    }
    
    public void setIdDogovor(int idDogovor) {
        this.idDogovor = idDogovor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_vraboten")
    public Vraboteni getVraboteni() {
        return this.vraboteni;
    }
    
    public void setVraboteni(Vraboteni vraboteni) {
        this.vraboteni = vraboteni;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="pocetok", nullable=false, length=13)
    public Date getPocetok() {
        return this.pocetok;
    }
    
    public void setPocetok(Date pocetok) {
        this.pocetok = pocetok;
    }

    
    @Column(name="plata", nullable=false, precision=17, scale=17)
    public double getPlata() {
        return this.plata;
    }
    
    public void setPlata(double plata) {
        this.plata = plata;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="kraj", nullable=false, length=13)
    public Date getKraj() {
        return this.kraj;
    }
    
    public void setKraj(Date kraj) {
        this.kraj = kraj;
    }

    
    @Column(name="aktiven", nullable=false)
    public short getAktiven() {
        return this.aktiven;
    }
    
    public void setAktiven(short aktiven) {
        this.aktiven = aktiven;
    }




}


