package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DopolniteliDeloviZaNaracka generated by hbm2java
 */
@Entity
@Table(name = "dopolniteli_delovi_za_naracka")
@Getter
@Setter
public class DopolniteliDeloviZaNaracka {

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "idNaracka", column = @Column(name = "id_naracka", nullable = false)),
            @AttributeOverride(name = "idDel", column = @Column(name = "id_del", nullable = false))})
    private DopolniteliDeloviZaNarackaId id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_del", nullable = false, insertable = false, updatable = false)
    private Delovi delovi;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_naracka", nullable = false, insertable = false, updatable = false)
    private Naracka naracka;
    @Column(name = "kolicina", nullable = false)
    private int kolicina;

    public DopolniteliDeloviZaNaracka() {
    }

    public DopolniteliDeloviZaNaracka(DopolniteliDeloviZaNarackaId id, Delovi delovi, Naracka naracka, int kolicina) {
        this.id = id;
        this.delovi = delovi;
        this.naracka = naracka;
        this.kolicina = kolicina;
    }



}


