package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EvidencijaNarackiIzraboteniDelovi generated by hbm2java
 */
@Entity
@Table(name = "evidencija_naracki_izraboteni_delovi")
@Getter
@Setter
public class EvidencijaNarackiIzraboteniDelovi{

    @EmbeddedId


    @AttributeOverrides({
            @AttributeOverride(name = "idEvidencija", column = @Column(name = "id_evidencija", nullable = false)),
            @AttributeOverride(name = "idDel", column = @Column(name = "id_del", nullable = false))})
    private EvidencijaNarackiIzraboteniDeloviId id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_del", nullable = false, insertable = false, updatable = false)
    private Delovi delovi;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_evidencija", nullable = false, insertable = false, updatable = false)
    private EvidencijaNaNaracki evidencijaNaNaracki;
    @Column(name = "br_na_zavrseni_delovi", nullable = false)
    private int brNaZavrseniDelovi;

    public EvidencijaNarackiIzraboteniDelovi() {
    }

    public EvidencijaNarackiIzraboteniDelovi(EvidencijaNarackiIzraboteniDeloviId id, Delovi delovi, EvidencijaNaNaracki evidencijaNaNaracki, int brNaZavrseniDelovi) {
        this.id = id;
        this.delovi = delovi;
        this.evidencijaNaNaracki = evidencijaNaNaracki;
        this.brNaZavrseniDelovi = brNaZavrseniDelovi;
    }

}


