package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EvidencijaSeOdnesuvaNaMebel generated by hbm2java
 */
@Entity
@Table(name = "evidencija_se_odnesuva_na_mebel")
@Getter
@Setter
public class EvidencijaSeOdnesuvaNaMebel  {


    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "evidencijaNaNaracki"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "id_evidencija", unique = true, nullable = false)
    private Long idEvidencija;
    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    private EvidencijaNaNaracki evidencijaNaNaracki;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_mebel", nullable = false)
    private Mebel mebel;
    @Column(name = "procenti_zavrsen", precision = 17, scale = 17)
    private Double procentiZavrsen;

    public EvidencijaSeOdnesuvaNaMebel() {
    }


    public EvidencijaSeOdnesuvaNaMebel(EvidencijaNaNaracki evidencijaNaNaracki, Mebel mebel) {
        this.evidencijaNaNaracki = evidencijaNaNaracki;
        this.mebel = mebel;
    }

    public EvidencijaSeOdnesuvaNaMebel(EvidencijaNaNaracki evidencijaNaNaracki, Mebel mebel, Double procentiZavrsen) {
        this.evidencijaNaNaracki = evidencijaNaNaracki;
        this.mebel = mebel;
        this.procentiZavrsen = procentiZavrsen;
    }

}


