package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ImaNapravenoServisId generated by hbm2java
 */
@Embeddable
public class ImaNapravenoServisId  implements java.io.Serializable {


     private int idServis;
     private int idMashina;

    public ImaNapravenoServisId() {
    }

    public ImaNapravenoServisId(int idServis, int idMashina) {
       this.idServis = idServis;
       this.idMashina = idMashina;
    }
   


    @Column(name="id_servis", nullable=false)
    public int getIdServis() {
        return this.idServis;
    }
    
    public void setIdServis(int idServis) {
        this.idServis = idServis;
    }


    @Column(name="id_mashina", nullable=false)
    public int getIdMashina() {
        return this.idMashina;
    }
    
    public void setIdMashina(int idMashina) {
        this.idMashina = idMashina;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImaNapravenoServisId) ) return false;
		 ImaNapravenoServisId castOther = ( ImaNapravenoServisId ) other; 
         
		 return (this.getIdServis()==castOther.getIdServis())
 && (this.getIdMashina()==castOther.getIdMashina());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdServis();
         result = 37 * result + this.getIdMashina();
         return result;
   }   


}


