package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ImaNapravenoServis generated by hbm2java
 */
@Entity
@Table(name="ima_napraveno_servis"
)
public class ImaNapravenoServis  implements java.io.Serializable {


     private ImaNapravenoServisId id;
     private Mashini mashini;
     private Date datum;
     private String zabeleska;
     private double cena;

    public ImaNapravenoServis() {
    }

    public ImaNapravenoServis(ImaNapravenoServisId id, Mashini mashini, Date datum, String zabeleska, double cena) {
       this.id = id;
       this.mashini = mashini;
       this.datum = datum;
       this.zabeleska = zabeleska;
       this.cena = cena;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idServis", column=@Column(name="id_servis", nullable=false) ), 
        @AttributeOverride(name="idMashina", column=@Column(name="id_mashina", nullable=false) ) } )
    public ImaNapravenoServisId getId() {
        return this.id;
    }
    
    public void setId(ImaNapravenoServisId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mashina", nullable=false, insertable=false, updatable=false)
    public Mashini getMashini() {
        return this.mashini;
    }
    
    public void setMashini(Mashini mashini) {
        this.mashini = mashini;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datum", nullable=false, length=13)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

    
    @Column(name="zabeleska", nullable=false)
    public String getZabeleska() {
        return this.zabeleska;
    }
    
    public void setZabeleska(String zabeleska) {
        this.zabeleska = zabeleska;
    }

    
    @Column(name="cena", nullable=false, precision=17, scale=17)
    public double getCena() {
        return this.cena;
    }
    
    public void setCena(double cena) {
        this.cena = cena;
    }




}


