package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import mk.ukim.finki.bazi.is_fagus.model.enumerations.Role;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Klienti generated by hbm2java
 */
@Entity
@Table(name = "klienti")
@Getter
@Setter
public class Klienti  {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_klient")
    private Long idKlient;

    @Column(name = "email")
    private String email;

    @Column(name = "ime")
    private String ime;

    @Column(name = "lozinka", length = 300)
    private String lozinka;
    @Column(name = "role")
    @Enumerated(EnumType.STRING)
    private Role role;

    @Column(name = "prezime")
    private String prezime;

    @Column(name = "korisnicko_ime")
    private String korisnickoIme;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "klienti")
    private Set<Naracka> narackas;

    public Klienti() {
    }

    public Klienti(String ime,
                   String prezime,
                   String korisnickoIme,
                   String lozinka,
                   String email) {
        this.email = email;
        this.ime = ime;
        this.lozinka = lozinka;
        this.role = Role.ROLE_CLIENT;
        this.prezime = prezime;
        this.korisnickoIme = korisnickoIme;
    }

}


