package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import mk.ukim.finki.bazi.is_fagus.model.enumerations.Role;

import javax.persistence.*;

/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(name = "korisnik")
@Getter
@Setter
public class Korisnik implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_korisnik")
    private Long idKorisnik;
    @Column(name = "email")
    private String email;

    @Column(name = "lozinka", length = 300)
    private String lozinka;

    @Column(name = "role")
    @Enumerated(value = EnumType.STRING)
    private Role role;

    @Column(name = "korisnicko_ime")
    private String korisnickoIme;



    public Korisnik() {
    }

    public Korisnik(String korisnickoIme, String lozinka, String email, Role role) {
        this.email = email;
        this.lozinka = lozinka;
        this.role = role;
        this.korisnickoIme = korisnickoIme;
    }


}


