package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * MashinaPripagaOddelenie generated by hbm2java
 */
@Entity
@Table(name="mashina_pripaga_oddelenie"
)
public class MashinaPripagaOddelenie  implements java.io.Serializable {


     private int idMashina;
     private Mashini mashini;
     private Oddelenija oddelenija;

    public MashinaPripagaOddelenie() {
    }

    public MashinaPripagaOddelenie(Mashini mashini, Oddelenija oddelenija) {
       this.mashini = mashini;
       this.oddelenija = oddelenija;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="mashini"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_mashina", unique=true, nullable=false)
    public int getIdMashina() {
        return this.idMashina;
    }
    
    public void setIdMashina(int idMashina) {
        this.idMashina = idMashina;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Mashini getMashini() {
        return this.mashini;
    }
    
    public void setMashini(Mashini mashini) {
        this.mashini = mashini;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_oddelenie", nullable=false)
    public Oddelenija getOddelenija() {
        return this.oddelenija;
    }
    
    public void setOddelenija(Oddelenija oddelenija) {
        this.oddelenija = oddelenija;
    }




}


