package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Getter;
import lombok.Setter;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Materijali generated by hbm2java
 */
@Entity
@Table(name = "materijali")
@Getter
@Setter
public class Materijali {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_materijal", unique = true, nullable = false)
    private Long idMaterijal;
    @Column(name = "velicina", nullable = false, precision = 17, scale = 17)
    private Double velicina;
    @Column(name = "naziv", nullable = false, length = 50)
    private String naziv;
    @Column(name = "dostapen_broj", nullable = false)
    private Integer dostapenBroj;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "materijali")
    private Set<DeloviIzraboteniOdMaterijal> deloviIzraboteniOdMaterijals = new HashSet<DeloviIzraboteniOdMaterijal>(0);

    public Materijali() {
    }


    public Materijali(Double velicina, String naziv, Integer dostapenBroj) {
        this.velicina = velicina;
        this.naziv = naziv;
        this.dostapenBroj = dostapenBroj;
    }


}


