package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Getter;
import lombok.Setter;


import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.io.Serializable;

/**
 * MebelSeSostoiOdDeloviId generated by hbm2java
 */
@Embeddable
@Getter
@Setter
public class MebelSeSostoiOdDeloviId implements Serializable {

    @Column(name = "id_mebel", nullable = false)
    private Long idMebel;
    @Column(name = "id_del", nullable = false)
    private Long idDel;

    public MebelSeSostoiOdDeloviId() {
    }

    public MebelSeSostoiOdDeloviId(Long idMebel, Long idDel) {
        this.idMebel = idMebel;
        this.idDel = idDel;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof MebelSeSostoiOdDeloviId)) return false;
        MebelSeSostoiOdDeloviId castOther = (MebelSeSostoiOdDeloviId) other;

        return (this.getIdMebel()==castOther.getIdMebel())
                && (this.getIdDel() == castOther.getIdDel());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdMebel().intValue();
        result = 37 * result + this.getIdDel().intValue();
        return result;
    }


}


