package mk.ukim.finki.bazi.is_fagus.model;

// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MebelSeSostoiOdDelovi generated by hbm2java
 */
@Entity
@Table(name="mebel_se_sostoi_od_delovi")
public class MebelSeSostoiOdDelovi  implements java.io.Serializable {


     private MebelSeSostoiOdDeloviId id;
     private Delovi delovi;
     private Mebel mebel;
     private int kolicina;

    public MebelSeSostoiOdDelovi() {
    }

    public MebelSeSostoiOdDelovi(MebelSeSostoiOdDeloviId id, Delovi delovi, Mebel mebel, int kolicina) {
       this.id = id;
       this.delovi = delovi;
       this.mebel = mebel;
       this.kolicina = kolicina;
    }
   
     @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idMebel", column=@Column(name="id_mebel", nullable=false) ), 
        @AttributeOverride(name="idDel", column=@Column(name="id_del", nullable=false) ) } )
    public MebelSeSostoiOdDeloviId getId() {
        return this.id;
    }
    
    public void setId(MebelSeSostoiOdDeloviId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_del", nullable=false, insertable=false, updatable=false)
    public Delovi getDelovi() {
        return this.delovi;
    }
    
    public void setDelovi(Delovi delovi) {
        this.delovi = delovi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_mebel", nullable=false, insertable=false, updatable=false)
    public Mebel getMebel() {
        return this.mebel;
    }
    
    public void setMebel(Mebel mebel) {
        this.mebel = mebel;
    }

    
    @Column(name="kolicina", nullable=false)
    public int getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(int kolicina) {
        this.kolicina = kolicina;
    }




}


