package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Menadzeri generated by hbm2java
 */
@Entity
@Table(name = "menadzeri")
@Getter
@Setter
public class Menadzeri {


    @Id
    @Column(name = "id_vraboten", unique = true, nullable = false)
    private Long idVraboten;

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    private Vraboteni vraboteni;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "menadzeri")
    private Set<Nalozi> nalozis = new HashSet<Nalozi>(0);

    public Menadzeri() {
    }

    public Menadzeri(Vraboteni vraboteni) {
        this.vraboteni = vraboteni;
    }

    public Menadzeri(Vraboteni vraboteni, Set<Nalozi> nalozis) {
        this.vraboteni = vraboteni;
        this.nalozis = nalozis;
    }

}


