package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * NaloziKreiraNaracka generated by hbm2java
 */
@Entity
@Table(name = "nalozi_kreira_naracka")
@Getter
@Setter
public class NaloziKreiraNaracka {


    @Id
    @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="nalozi"))
    @GeneratedValue(generator="generator")
    @Column(name = "id_nalog", unique = true, nullable = false)
    private Long idNalog;
    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    private Nalozi nalozi;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_naracka", nullable = false)
    private Naracka naracka;

    public NaloziKreiraNaracka() {
    }

    public NaloziKreiraNaracka(Nalozi nalozi,Naracka naracka){
        this.nalozi=nalozi;
        this.naracka=naracka;
    }
}


