package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NarackaSeSostoiOdMebelId generated by hbm2java
 */
@Embeddable
@Data
public class NarackaSeSostoiOdMebelId implements java.io.Serializable {

    @Column(name = "id_mebel", nullable = false)
    private Long idMebel;
    @Column(name = "id_naracka", nullable = false)
    private Long idNaracka;

    public NarackaSeSostoiOdMebelId() {
    }

    public NarackaSeSostoiOdMebelId(Long idMebel, Long idNaracka) {
        this.idMebel = idMebel;
        this.idNaracka = idNaracka;
    }

    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof NarackaSeSostoiOdMebelId)) return false;
        NarackaSeSostoiOdMebelId castOther = (NarackaSeSostoiOdMebelId) other;

        return (this.getIdMebel() == castOther.getIdMebel())
                && (this.getIdNaracka() == castOther.getIdNaracka());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdMebel().intValue();
        result = 37 * result + this.getIdNaracka().intValue();
        return result;
    }


}


