package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Getter;
import lombok.Setter;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NarackaSeSostoiOdMebel generated by hbm2java
 */
@Entity
@Table(name = "naracka_se_sostoi_od_mebel")
@Getter
@Setter
public class NarackaSeSostoiOdMebel  {

    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "idMebel", column = @Column(name = "id_mebel", nullable = false)),
            @AttributeOverride(name = "idNaracka", column = @Column(name = "id_naracka", nullable = false))})
    private NarackaSeSostoiOdMebelId id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_mebel", nullable = false, insertable = false, updatable = false)
    private Mebel mebel;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_naracka", nullable = false, insertable = false, updatable = false)
    private Naracka naracka;
    @Column(name = "kolicina", nullable = false)
    private Integer kolicina;

    public NarackaSeSostoiOdMebel() {
    }

    public NarackaSeSostoiOdMebel(NarackaSeSostoiOdMebelId id,
                                  Mebel mebel,
                                  Naracka naracka,
                                  Integer kolicina) {
        this.id = id;
        this.mebel = mebel;
        this.naracka = naracka;
        this.kolicina = kolicina;
    }

}


