package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Naracka generated by hbm2java
 */
@Entity
@Table(name = "naracka")
@Getter
@Setter
public class Naracka  {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_naracka")
    private Long idNaracka;
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_klient", nullable = false)
    private Klienti klienti;

    @Temporal(TemporalType.DATE)
    @Column(name = "datum_napravena", nullable = false, length = 13)
    private Date datumNapravena;
    @Temporal(TemporalType.DATE)
    @Column(name = "datum_isporacana", length = 13)
    private Date datumIsporacana;
    @Column(name = "naslov", nullable = false, length = 100)
    private String naslov;
    @Column(name = "opis", nullable = false)
    private String opis;
    @Column(name = "vkupna_cena", precision = 17, scale = 17)
    private Double vkupnaCena;
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "naracka")
    private Set<EvidencijaNaNaracki> evidencijaNaNarackis= new HashSet<>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "naracka")
    private Set<DopolniteliDeloviZaNaracka> dopolniteliDeloviZaNarackas = new HashSet<>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "naracka")
    private Set<NarackaSeSostoiOdMebel> narackaSeSostoiOdMebelsSostoiOdMebel =  new HashSet<>(0);
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "naracka")
    private Set<NaloziKreiraNaracka> naloziKreiraNarackas =new HashSet<>();

    public Naracka() {
    }


    public Naracka(Klienti klienti, Date datumNapravena, String naslov, String opis) {
        this.klienti = klienti;
        this.datumNapravena = datumNapravena;
        this.naslov = naslov;
        this.opis = opis;
    }


}


