package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Oddelenija generated by hbm2java
 */
@Entity
@Table(name="oddelenija"
)
public class Oddelenija  implements java.io.Serializable {


     private int idOddelenie;
     private String naziv;
     private Set<VraboteniVoProizvodstvoRabotiVoOddelenija> vraboteniVoProizvodstvoRabotiVoOddelenijas = new HashSet<VraboteniVoProizvodstvoRabotiVoOddelenija>(0);
     private Set<MashinaPripagaOddelenie> mashinaPripagaOddelenies = new HashSet<MashinaPripagaOddelenie>(0);

    public Oddelenija() {
    }

	
    public Oddelenija(int idOddelenie, String naziv) {
        this.idOddelenie = idOddelenie;
        this.naziv = naziv;
    }
    public Oddelenija(int idOddelenie, String naziv, Set<VraboteniVoProizvodstvoRabotiVoOddelenija> vraboteniVoProizvodstvoRabotiVoOddelenijas, Set<MashinaPripagaOddelenie> mashinaPripagaOddelenies) {
       this.idOddelenie = idOddelenie;
       this.naziv = naziv;
       this.vraboteniVoProizvodstvoRabotiVoOddelenijas = vraboteniVoProizvodstvoRabotiVoOddelenijas;
       this.mashinaPripagaOddelenies = mashinaPripagaOddelenies;
    }
   
     @Id 

    
    @Column(name="id_oddelenie", unique=true, nullable=false)
    public int getIdOddelenie() {
        return this.idOddelenie;
    }
    
    public void setIdOddelenie(int idOddelenie) {
        this.idOddelenie = idOddelenie;
    }

    
    @Column(name="naziv", nullable=false, length=30)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oddelenija")
    public Set<VraboteniVoProizvodstvoRabotiVoOddelenija> getVraboteniVoProizvodstvoRabotiVoOddelenijas() {
        return this.vraboteniVoProizvodstvoRabotiVoOddelenijas;
    }
    
    public void setVraboteniVoProizvodstvoRabotiVoOddelenijas(Set<VraboteniVoProizvodstvoRabotiVoOddelenija> vraboteniVoProizvodstvoRabotiVoOddelenijas) {
        this.vraboteniVoProizvodstvoRabotiVoOddelenijas = vraboteniVoProizvodstvoRabotiVoOddelenijas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="oddelenija")
    public Set<MashinaPripagaOddelenie> getMashinaPripagaOddelenies() {
        return this.mashinaPripagaOddelenies;
    }
    
    public void setMashinaPripagaOddelenies(Set<MashinaPripagaOddelenie> mashinaPripagaOddelenies) {
        this.mashinaPripagaOddelenies = mashinaPripagaOddelenies;
    }




}


