package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * VraboteniSeKorisnici generated by hbm2java
 */
@Entity
@Table(name = "vraboteni_se_korisnici")
@Getter
@Setter
public class VraboteniSeKorisnici implements java.io.Serializable {

    @Column(name = "id_vraboten", unique = true, nullable = false)
    @Id
    private Long idVraboten;
    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    private Vraboteni vraboteni;

    @Column(name = "id_korisnik")
    private Long idKorisnik;

    public VraboteniSeKorisnici() {
    }


    public VraboteniSeKorisnici(Vraboteni vraboteni) {
        this.vraboteni = vraboteni;
    }

    public VraboteniSeKorisnici(Vraboteni vraboteni, Long idKorisnik) {
        this.vraboteni = vraboteni;
        this.idKorisnik = idKorisnik;
    }




}


