package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * VraboteniVoProizvodstvo generated by hbm2java
 */
@Entity
@Table(name="vraboteni_vo_proizvodstvo"
)
public class VraboteniVoProizvodstvo  implements java.io.Serializable {


     private Long idVraboten;
     private Vraboteni vraboteni;
     private VraboteniVoProizvodstvoRabotiNaMashina vraboteniVoProizvodstvoRabotiNaMashina;
     private VraboteniVoProizvodstvoRabotiVoOddelenija vraboteniVoProizvodstvoRabotiVoOddelenija;

    public VraboteniVoProizvodstvo() {
    }

	
    public VraboteniVoProizvodstvo(Vraboteni vraboteni) {
        this.vraboteni = vraboteni;
    }
    public VraboteniVoProizvodstvo(Vraboteni vraboteni, VraboteniVoProizvodstvoRabotiNaMashina vraboteniVoProizvodstvoRabotiNaMashina, VraboteniVoProizvodstvoRabotiVoOddelenija vraboteniVoProizvodstvoRabotiVoOddelenija) {
       this.vraboteni = vraboteni;
       this.vraboteniVoProizvodstvoRabotiNaMashina = vraboteniVoProizvodstvoRabotiNaMashina;
       this.vraboteniVoProizvodstvoRabotiVoOddelenija = vraboteniVoProizvodstvoRabotiVoOddelenija;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="vraboteni"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="id_vraboten", unique=true, nullable=false)
    public Long getIdVraboten() {
        return this.idVraboten;
    }
    
    public void setIdVraboten(Long idVraboten) {
        this.idVraboten = idVraboten;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Vraboteni getVraboteni() {
        return this.vraboteni;
    }
    
    public void setVraboteni(Vraboteni vraboteni) {
        this.vraboteni = vraboteni;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteniVoProizvodstvo")
    public VraboteniVoProizvodstvoRabotiNaMashina getVraboteniVoProizvodstvoRabotiNaMashina() {
        return this.vraboteniVoProizvodstvoRabotiNaMashina;
    }
    
    public void setVraboteniVoProizvodstvoRabotiNaMashina(VraboteniVoProizvodstvoRabotiNaMashina vraboteniVoProizvodstvoRabotiNaMashina) {
        this.vraboteniVoProizvodstvoRabotiNaMashina = vraboteniVoProizvodstvoRabotiNaMashina;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteni")
    public VraboteniVoProizvodstvoRabotiVoOddelenija getVraboteniVoProizvodstvoRabotiVoOddelenija() {
        return this.vraboteniVoProizvodstvoRabotiVoOddelenija;
    }
    
    public void setVraboteniVoProizvodstvoRabotiVoOddelenija(VraboteniVoProizvodstvoRabotiVoOddelenija vraboteniVoProizvodstvoRabotiVoOddelenija) {
        this.vraboteniVoProizvodstvoRabotiVoOddelenija = vraboteniVoProizvodstvoRabotiVoOddelenija;
    }




}


