package mk.ukim.finki.bazi.is_fagus.model;
// Generated Sep 26, 2021, 3:23:30 AM by Hibernate Tools 4.3.5.Final


import lombok.Getter;
import lombok.Setter;
import mk.ukim.finki.bazi.is_fagus.model.enumerations.Role;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Vraboteni generated by hbm2java
 */
@Entity
@Table(name="vraboteni")
@Getter
@Setter
public class Vraboteni  {

    @Id
    @Column(name="id_vraboten", unique=true, nullable=false)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Long idVraboten;

    @Column(name="ime", nullable=false, length=100)
     private String ime;
    @Column(name="prezime", nullable=false, length=100)
     private String prezime;
    @Column(name="embg", nullable=false, length=13)
     private String embg;
    @Temporal(TemporalType.DATE)
    @Column(name="datum_ragjanje", nullable=false, length=13)
     private Date datumRagjanje;
    @Column(name="obrazovanie", nullable=false, length=100)
     private String obrazovanie;

    @Column(name="role")
     private Role role;
    @OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteni")
     private Direktor direktor;

    @OneToMany(fetch=FetchType.LAZY, mappedBy="menadzeri")
     private Set<Nalozi> nalozis = new HashSet<Nalozi>(0);
    @OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteni")
     private Magacioneri magacioneri;
    @OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteni")
     private VraboteniVoProizvodstvoRabotiVoOddelenija vraboteniVoProizvodstvoRabotiVoOddelenija;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="vraboteni")
    private Set<Dogovori> dogovoris = new HashSet<Dogovori>(0);

    @OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteni")
     private VraboteniSeKorisnici vraboteniSeKorisnici;
    @OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteni")
     private Menadzeri menadzeri;

    @OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteni")
     private VraboteniVoProizvodstvo vraboteniVoProizvodstvo;
    @OneToOne(fetch=FetchType.LAZY, mappedBy="vraboteni")
     private Shefovi shefovi;

    public Vraboteni() {
    }

	
    public Vraboteni( String ime, String prezime, String embg, Date datumRagjanje, String obrazovanie) {
        this.ime = ime;
        this.prezime = prezime;
        this.embg = embg;
        this.datumRagjanje = datumRagjanje;
        this.obrazovanie = obrazovanie;
    }


}


